export const ContactData = [
  {
    id: "1",
    name: "Rohit Sharma",
    number: "9848012345",
    email: "Sharma@gmail.com",
    gender: "male",
    type: "business",
  },
  {
    id: "2",
    name: "Shekar Dawan",
    number: "9988776655",
    email: "dawan@gmail.com",
    gender: "male",
    type: "business",
  },
  {
    id: "3",
    name: "Virat Kohli",
    number: "6655443322",
    email: "Kohli@gmail.com",
    gender: "male",
    type: "business",
  },
  {
    id: "4",
    name: "Rishab Pant",
    number: "9876543210",
    email: "pant@gmail.com",
    gender: "male",
    type: "business",
  },
  {
    id: "5",
    name: "Suresh Raina",
    number: "6633552211",
    email: "Raina@gmail.com",
    gender: "male",
    type: "business",
  },
  {
    id: "6",
    name: "Ashwin Sharma",
    number: "9875654321",
    email: "ashwin@gmail.com",
    gender: "male",
    type: "personal",
  },
  {
    id: "7",
    name: "Smriti Mandhana ",
    number: "665*****22",
    email: "Mandhana@gmail.com",
    gender: "female",
    type: "personal",
  },
  {
    id: "8",
    name: "Poonam Yadav ",
    number: "987*****10",
    email: "Poonamyadav@gmail.com",
    gender: "female",
    type: "personal",
  },
];
